### ISSUE TITLE
dataset  Twitter2017

### ISSUE THREAD

**Issue by dwchen123** [jefferyYu/UMT#6]
你好，Twitter2017数据集里的图片是不是没有上传好，我下载了几次都会有部分图片不全
![image](https://user-images.githubusercontent.com/55351522/89125286-fcc1b380-d50f-11ea-99df-e686a73c1c21.png)

**Comment by jefferyYu** [comment]
Hi there,

For both Twitter-2015 and Twitter-2017 datasets obtained by us, there are a few smaples with very small or broken images. As shown in the begining our running log files, there are a small number of problematic images in the training, dev, test sets. In our experiments, we have replaced these problematic images with a special image which contains a text box "Image Not Found". 

Hope it clarifies your concern.
